language: ruby
rvm:
  - 2.4.1

before_install:
  - gem update --system
  - gem install bundler

install: bundle install

script: ./_scripts/publish.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - lftp

branches:
  only:
    - master

sudo: false

dist: xenial

cache: bundler

notifications:
  email: false
