# Site settings
title: XTremeGaida
email: redacted@redacted.com
description: >-
  Pending cool site description. Everything is awesome.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: xtremegaida
github_username: xtremegaida

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - run.bat
  - _scripts
  - node_modules
  - vendor
